# This is the configuration file for the acdc reward model.
project_name: acdc_reward_model
seed: 0 
ckpt_dir: ./checkpoints_rm

# data path <replace with your own paths>
datadir: <your_acdc_data_dir>

# task
task: reconstruction
combine_class_recon_splits: True
ignore_kspace: False
ignore_image: False
dataset: acdc
use_weighted_sampler: False 
train_sampler_filename: None
image_shape: [256, 256]
kspace_shape: [256, 256]
in_channels: 1

# backbone model
model_type: 'resnet50'
pretrained: imagenet
dropout: 0.1

# optimization
n_epochs: 400
num_workers: 3
optimizer: adamw
dropout_rate: 0.1
grad_clip_val: 0.0
batch_size: 32  
val_batch_size: 32
test_batch_size: 32
accumulate_grad_batches: 1
lr: 0.0001
weight_decay: 0.1
lr_step_size: 3
lr_gamma: 0.1
lr_scheduler: true
k_fraction: 0.1
center_fraction: 0.05
mask_type: vds
val_fn_type: MI
greedy_search: True
min_sampling_rate: 0.05
max_sampling_rate: 1.0
early_stopping_greedy: True
val_shuffle : False

# checkpoint
resume_train: False
ckpt_path: None